# Generated by Django 4.2.18 on 2025-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_web', '0002_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
